# Site settings
title: Yiqiao Jin
SEOTitle: Yiqiao Jin | UCLA
header-img: img/Royce.jpg
email: ahren2040@g.ucla.edu
description: "Research Intern at Microsoft Research Asia (MSRA)"
keyword: "Recommender Systems, Graph-based Recommendation, Graph Representation Learning, GNN, NLP"
url: "https://ahren09.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
# weibo_username:     Ahren09
zhihu_username:     ahrenqiao
github_username:    Ahren09
# twitter_username:   huxpro
# facebook_username:  huxpro
linkedin_username:  ahren-jin



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# Ahren: Turned off Disqus comment area for now
# disqus_username: hux

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: ahren09.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "靳轶乔"
sidebar-avatar: /img/Ahren/BJ.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

publications: [
  {
    title: "Towards Fine-Grained Reasoning for Fake News Detection",
    image: "img/Publications/FinerFact.png",
    authors: [
      {
        name: "Yiqiao Jin",
        url: "https://www.linkedin.com/in/ahren-jin/"
      },
      {
        name: "Xiting Wang",
        url: "https://www.microsoft.com/en-us/research/people/xitwan/"
      },
      {
        name: "Ruichao Yang",
        url: ""
      },
      {
        name: "Yizhou Sun",
        url: "http://web.cs.ucla.edu/~yzsun/"
      },
      {
        name: "Wei Wang",
        url: "http://web.cs.ucla.edu/~weiwang/"
      },
      {
        name: "Hao Liao",
        url: "https://scholar.google.ch/citations?user=Tu5ZuREAAAAJ&hl=en"
      },
      {
        name: "Xing Xie",
        url: "https://www.microsoft.com/en-us/research/people/xingx/"
      },

    ],
    status: "Preprint. Under Review."
  },
  {
    title: "Deep Graph Similarity Learning with Spectral Support",
    image: "img/Publications/WaveSim.png",
    authors: [
      {
        name: "Feng Shi",
        url: "https://scholar.google.com/citations?user=urVyCJwAAAAJ&hl=en"
      },
      {
        name: "Yiqiao Jin",
        url: "https://www.linkedin.com/in/ahren-jin/"
      },
      {
        name: "Tianyang Liu",
        url: "https://www.linkedin.com/in/tianyang-liu-336884198/"
      },
      {
        name: "Songchun Zhu",
        url: "http://www.stat.ucla.edu/~sczhu/"
      },

    ],
    status: "Preprint."
  }
  
]

whatsnew: [
  {
    time: "Sept. 17th, 2021",
    desc: "I completed my internship at Microsoft Research Asia (MSRA)"
  }, {
    time: "Sept. 15th, 2021",
    desc: "I wrote a help doc for incoming interns at MSRA SC Group. You can read part of it from <a>here</a>"
  }, {
    time: "Dec. 22th, 2020",
    desc: "I started to work as a research intern at MSRA"
  }, {
    time: "Sept. 4th, 2020",
    desc: "I completed my SDE internship at Amazon (FBA IAR Team)"
  }
]

interests: [
  "Recommender Systems & Graph-based Recommendation",
  "Graph Representation Learning",
  "Graph Neural Networks",
  "Natural Language Processing & Text Mining"
]
